# Generated by Django 5.2.7 on 2025-11-22 06:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendador', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorito',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='favorito',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='genero_preferido',
            field=models.CharField(blank=True, choices=[('action', 'Action'), ('adventure', 'Adventure'), ('role-playing-games-rpg', 'RPG'), ('indie', 'Indie'), ('shooter', 'Shooter'), ('sports', 'Sports'), ('strategy', 'Strategy'), ('simulation', 'Simulation')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='plataforma_preferida',
            field=models.CharField(blank=True, choices=[('4', 'PC'), ('187', 'PS5'), ('1', 'Xbox One'), ('18', 'PS4'), ('7', 'Switch'), ('3', 'iOS'), ('21', 'Android')], max_length=50, null=True),
        ),
    ]
